.setup-ssh:
  before_script:
    - 'which ssh-agent || ( apk add --no-cache openssh )'
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    

stages:
  - build
  - publish
  - deploy
  - clean

variables:
  GCP_PROJECT_ID: "propensi-451504"
  IMAGE_REPO: "gcr.io/$GCP_PROJECT_ID"
  IMAGE_DOCKER_DIND: docker:27.3.1-alpine3.20
  IMAGE_NODE: node:18-alpine

# Build job for Vue.js frontend
build-frontend:
  stage: build
  script:
    - docker info
    - echo "Building Vue.js frontend..."
    - cd kamis-fe
    - npm install --progress=false
    - npm run build
  artifacts:
    paths:
      - frontend/dist

# Publish job for Vue.js frontend
publish-frontend:
  image: $IMAGE_DOCKER_DIND
  stage: publish
  dependencies:
    - build-frontend
  script:
    - echo "Building Docker image for Vue.js frontend..."
    - echo "Checking GCLOUD_SERVICE_KEY"
    - echo $GCLOUD_SERVICE_KEY | base64 -d | docker login -u _json_key --password-stdin https://gcr.io || true
    - docker build -t $IMAGE_REPO/frontend:latest -f Dockerfile .
    - echo "Pushing Docker image to Google Container Registry..."
    - docker push $IMAGE_REPO/frontend:latest

# Deploy job for all services
deploy-services:
  stage: deploy
  dependencies:
    - publish-frontend
    # (Include other services as dependencies...)
  extends: .setup-ssh
  script:
    - echo "Deploying services to GCP VM..."
    - ssh "$DEPLOY_USERNAME@$DEPLOY_SERVER" "mkdir -p ~/microservices-deploy/"
    - rsync -rahv $CI_PROJECT_DIR/docker-compose-deploy.yml "$DEPLOY_USERNAME@$DEPLOY_SERVER:~/microservices-deploy/"
    - ssh "$DEPLOY_USERNAME@$DEPLOY_SERVER" "
        cd ~/microservices-deploy/ &&
        docker compose -f docker-compose-deploy.yml pull &&
        docker compose -f docker-compose-deploy.yml up -d --remove-orphans"

cleaning:
  stage: clean
  dependencies:
    - deploy-services
  extends: .setup-ssh
  script:
    - echo "Cleaning up unused Docker resources..."
    - ssh "$DEPLOY_USERNAME@$DEPLOY_SERVER" "docker system prune -af"
