services:
  frontend:
    container_name: frontend-kamis
    image: gcr.io/propensi-451504/frontend:latest
    ports:
      - '80:5173'
    restart: 'always'
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
